## Part 1: Preprocessing

In [32]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras import layers

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder



In [33]:

#  Import and read the attrition data
attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')
attrition_df.head()

Age Attrition     BusinessTravel              Department  DistanceFromHome  \
0   41       Yes      Travel_Rarely                   Sales                 1   
1   49        No  Travel_Frequently  Research & Development                 8   
2   37       Yes      Travel_Rarely  Research & Development                 2   
3   33        No  Travel_Frequently  Research & Development                 3   
4   27        No      Travel_Rarely  Research & Development                 2   

   Education EducationField  EnvironmentSatisfaction  HourlyRate  \
0          2  Life Sciences                        2          94   
1          1  Life Sciences                        3          61   
2          2          Other                        4          92   
3          4  Life Sciences                        4          56   
4          1        Medical                        1          40   

   JobInvolvement  ...  PerformanceRating RelationshipSatisfaction  \
0               3  ...                  3                        1   
1               2  ...                  4                        4   
2               2  ...                  3                        2   
3               3  ...                  3                        3   
4               3  ...                  3                        4   

   StockOptionLevel TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  \
0                 0                 8                      0               1   
1                 1                10                      3               3   
2                 0                 7                      3               3   
3                 0                 8                      3               3   
4                 1                 6                      3               3   

   YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
0               6                   4                        0   
1              10                   7                        1   
2               0                   0                        0   
3               8                   7                        3   
4               2                   2                        2   

   YearsWithCurrManager  
0                     5  
1                     7  
2                     0  
3                     0  
4                     2  

[5 rows x 27 columns]

In [34]:
# Determine the number of unique values in each column
attrition_df.nunique()

Age                         43
Attrition                    2
BusinessTravel               3
Department                   3
DistanceFromHome            29
Education                    5
EducationField               6
EnvironmentSatisfaction      4
HourlyRate                  71
JobInvolvement               4
JobLevel                     5
JobRole                      9
JobSatisfaction              4
MaritalStatus                3
NumCompaniesWorked          10
OverTime                     2
PercentSalaryHike           15
PerformanceRating            2
RelationshipSatisfaction     4
StockOptionLevel             4
TotalWorkingYears           40
TrainingTimesLastYear        7
WorkLifeBalance              4
YearsAtCompany              37
YearsInCurrentRole          19
YearsSinceLastPromotion     16
YearsWithCurrManager        18
dtype: int64

In [35]:
# Create y_df with the Attrition and Department columns
y_df = attrition_df[['Attrition', 'Department']]
y_df.head()

Attrition              Department
0       Yes                   Sales
1        No  Research & Development
2       Yes  Research & Development
3        No  Research & Development
4        No  Research & Development

In [36]:
# Create a list of at least 10 column names to use as X data
columns_list = ['Education', 'Age', 'DistanceFromHome','JobSatisfaction',
                'OverTime', 'StockOptionLevel', 'WorkLifeBalance',
                'YearsAtCompany', 'YearsSinceLastPromotion', 'NumCompaniesWorked']

# Create X_df using your selected columns
X_df = attrition_df[columns_list]

# Show the data types for X_df
X_df.dtypes

Education                   int64
Age                         int64
DistanceFromHome            int64
JobSatisfaction             int64
OverTime                   object
StockOptionLevel            int64
WorkLifeBalance             int64
YearsAtCompany              int64
YearsSinceLastPromotion     int64
NumCompaniesWorked          int64
dtype: object

In [38]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_df, y_df, random_state=7)

In [39]:
# Convert your X data to numeric data types however you see fit
# Add new code cells as necessary
display(X_train.dtypes)
X_test.dtypes


Education                   int64
Age                         int64
DistanceFromHome            int64
JobSatisfaction             int64
OverTime                   object
StockOptionLevel            int64
WorkLifeBalance             int64
YearsAtCompany              int64
YearsSinceLastPromotion     int64
NumCompaniesWorked          int64
dtype: object

Education                   int64
Age                         int64
DistanceFromHome            int64
JobSatisfaction             int64
OverTime                   object
StockOptionLevel            int64
WorkLifeBalance             int64
YearsAtCompany              int64
YearsSinceLastPromotion     int64
NumCompaniesWorked          int64
dtype: object

In [40]:
# Checking for null values
nulls = X_train['OverTime'].isna().sum()
print(nulls)

0


In [41]:
nulls_test = X_test['OverTime'].isna().sum()
print(nulls_test)

0


In [42]:
# Checking for unique values in both the train and test datasets
print("Unique values in X_train['OverTime']:", X_train['OverTime'].unique())
print("Unique values in X_test['OverTime']:", X_test['OverTime'].unique())

Unique values in X_train['OverTime']: ['Yes' 'No']
Unique values in X_test['OverTime']: ['No' 'Yes']


In [43]:
# Using the OneHotEncoder on the object column.
encoder = OneHotEncoder(sparse_output=False, drop='first')
X_train['OverTime'] = encoder.fit_transform(X_train[['OverTime']])
display(X_train['OverTime'].value_counts())

# Transforming the Overtime column on the X_test dataset. 
X_test['OverTime'] = encoder.transform(X_test[['OverTime']])
display(X_test['OverTime'].value_counts())

OverTime
0.0    789
1.0    313
Name: count, dtype: int64

OverTime
0.0    265
1.0    103
Name: count, dtype: int64

In [45]:
# Create a StandardScaler
scaler = StandardScaler()

# Fit the StandardScaler to the training data
scaler.fit(X_train)

# Scale the training and testing data
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

display(X_train_scaled[:5])
X_test_scaled[:5]

array([[-0.89593832,  0.32212245, -0.15544147,  1.17224457,  1.58769228,
        -0.93200983,  0.33713488, -0.8086699 , -0.04658669,  0.12990505],
       [ 2.03380657, -1.09430673, -0.15544147,  0.26887847, -0.62984497,
         2.58536973,  0.33713488, -0.64705324, -0.35962653, -0.6720858 ],
       [ 0.08064331,  0.10421027, -0.40050083,  1.17224457,  1.58769228,
         2.58536973,  0.33713488,  0.96911329, -0.35962653,  1.73388676],
       [ 0.08064331, -0.00474582, -0.76808988,  1.17224457, -0.62984497,
        -0.93200983,  0.33713488, -0.32381994, -0.35962653, -0.27109037],
       [-0.89593832, -0.222658  , -0.27797115,  1.17224457, -0.62984497,
         0.24045002, -1.07549873, -0.97028655, -0.67266636, -0.6720858 ]])

array([[ 0.08064331, -0.87639454, -0.89061956, -0.63448762, -0.62984497,
         0.24045002,  0.33713488, -0.32381994, -0.67266636, -1.07308123],
       [-0.89593832, -0.65848236,  2.41768186, -0.63448762, -0.62984497,
        -0.93200983,  1.7497685 , -0.32381994, -0.35962653, -1.07308123],
       [ 0.08064331, -0.44057018, -0.52303051,  0.26887847,  1.58769228,
        -0.93200983,  0.33713488, -0.97028655, -0.67266636, -0.6720858 ],
       [ 0.08064331, -0.44057018,  0.57973663, -0.63448762, -0.62984497,
         0.24045002,  0.33713488,  0.16103002, -0.35962653, -0.6720858 ],
       [ 1.05722494, -0.33161409, -1.01314924, -1.53785371, -0.62984497,
         1.41290988,  0.33713488, -0.48543659, -0.35962653,  0.9318959 ]])

In [46]:
# Create a OneHotEncoder for the Department column
oh_encoder_dept = OneHotEncoder(sparse_output=False, drop=None, handle_unknown='ignore')

# Fit the encoder to the training data
oh_encoder_dept.fit(y_train[['Department']])

# Create two new variables by applying the encoder
# to the training and testing data
y_department_train = oh_encoder_dept.transform(y_train[['Department']])
y_department_test = oh_encoder_dept.transform(y_test[['Department']])

display(y_department_train[:5])
y_department_test[:5]



array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.]])

In [47]:
# Create a OneHotEncoder for the Attrition column
oh_encoder_attr = OneHotEncoder(sparse_output=False, handle_unknown='ignore')

# Fit the encoder to the training data
oh_encoder_attr.fit(y_train[['Attrition']])

# Create two new variables by applying the encoder
# to the training and testing data
y_attrition_train = oh_encoder_attr.transform(y_train[['Attrition']])
y_attrition_test = oh_encoder_attr.transform(y_test[['Attrition']])

display(y_attrition_train[:5])
y_attrition_test[:5]

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.]])

array([[1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.]])

## Part 2: Create, Compile, and Train the Model

In [48]:
# Find the number of columns in the X training data.
input_columns = len(X_train.columns)

# Create the input layer
input_layer = layers.Input(shape=(input_columns,), name='input_layer')

# Create at least two shared layers
shared1 = layers.Dense(64, activation='relu', name='shared1')(input_layer)
shared2 = layers.Dense(128, activation='relu', name='shared2')(shared1)


In [49]:
# Create a branch for Department
# with a hidden layer and an output layer

# Create the hidden layer
department_hidden = layers.Dense(32, activation='relu', name='department_hidden')(shared2)

# Create the output layer
department_output = layers.Dense(3, activation='softmax', name='department_output')(department_hidden)

In [50]:
# Create a branch for Attrition
# with a hidden layer and an output layer

# Create the hidden layer
attrition_hidden = layers.Dense(32, activation='relu', name='attrition_hidden')(shared2)

# Create the output layer
attrition_output = layers.Dense(2, activation='sigmoid', name='attrition_output')(attrition_hidden)

In [51]:
# Create the model
nn_model = Model(inputs=input_layer, outputs=[attrition_output, department_output])

# Compile the model
nn_model.compile(optimizer='adam', loss={'department_output' : 'categorical_crossentropy',
                                    'attrition_output' : 'binary_crossentropy'},
                                   metrics={'department_output' : 'accuracy',
                                    'attrition_output' : 'accuracy'})

# Summarize the model
nn_model.summary()

Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer         │ (None, 10)        │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ shared1 (Dense)     │ (None, 64)        │        704 │ input_layer[0][0] │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ shared2 (Dense)     │ (None, 128)       │      8,320 │ shared1[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ attrition_hidden    │ (None, 32)        │      4,128 │ shared2[0][0]     │
│ (Dense)             │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ department_hidden   │ (None, 32)        │      4,128 │ shared2[0][0]     │
│ (Dense)             │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ attrition_output    │ (None, 2)         │         66 │ attrition_hidden… │
│ (Dense)             │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ department_output   │ (None, 3)         │         99 │ department_hidde… │
│ (Dense)             │                   │            │                   │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 17,445 (68.14 KB)

 Trainable params: 17,445 (68.14 KB)

 Non-trainable params: 0 (0.00 B)

In [52]:
# Train the model
nn_model.fit(X_train_scaled, {'department_output' : y_department_train,
                    'attrition_output' : y_attrition_train},
                    epochs=100,
                    batch_size=32,
                    validation_split=0.2)

Epoch 1/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 4s 27ms/step - attrition_output_accuracy: 0.8337 - attrition_output_loss: 0.5773 - department_output_accuracy: 0.3864 - department_output_loss: 1.0748 - loss: 1.6515 - val_attrition_output_accuracy: 0.8552 - val_attrition_output_loss: 0.4134 - val_department_output_accuracy: 0.6606 - val_department_output_loss: 0.8038 - val_loss: 1.2185
Epoch 2/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - attrition_output_accuracy: 0.8277 - attrition_output_loss: 0.4458 - department_output_accuracy: 0.6354 - department_output_loss: 0.8144 - loss: 1.2603 - val_attrition_output_accuracy: 0.8552 - val_attrition_output_loss: 0.3752 - val_department_output_accuracy: 0.6606 - val_department_output_loss: 0.8010 - val_loss: 1.1774
Epoch 3/100
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - attrition_output_accuracy: 0.8366 - attrition_output_loss: 0.3843 - department_output_accuracy: 0.6469 - department_output_loss: 0.7945 - loss: 1.1789 - val_attrition_output_accuracy: 0.8643 

In [73]:
# Evaluate the model with the testing data
test_result = nn_model.evaluate(X_test_scaled, {'department_output' : y_department_test,
                                                'attrition_output' : y_attrition_test})
test_result

12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.8333 - attrition_output_loss: 1.6157 - department_output_accuracy: 0.5641 - department_output_loss: 2.0985 - loss: 3.7269 


[3.885582685470581,
 1.5405950546264648,
 2.2625410556793213,
 0.8260869383811951,
 0.5570651888847351]

In [74]:
# Print the model evaluation scores.
print(f'Attrition output accuracy: {test_result[3]}')
print(f'Department output accuracy: {test_result[4]}')

Attrition output accuracy: 0.8260869383811951
Department output accuracy: 0.5570651888847351


# Summary

In the provided space below, briefly answer the following questions.

1. Is accuracy the best metric to use on this data? Why or why not?

2. What activation functions did you choose for your output layers, and why?

3. Can you name a few ways that this model might be improved?

YOUR ANSWERS HERE

1. In my opinion, I think it would not be very ideal because there is the possibility of false positives and false negatives which our accuracy metric does not distinguish between.

2. For the department, I used the softmax activation function while for the attrition, I used the sigmoid activation function. I used softmax because I was trying to predict whether some employees may be better suited to other departments, which is a multi-class classification and therefore, we are indicating the suitability of the employees in the multiple different departments.
For the attrition, I used the sigmoid function because I was dealing with a binary classification issue, whereby I am trying to predict whether they will leave or not, hence the sigmoid function which is ideal in classifying binary scenarios.

3. To improve this model, we could create/include new features which may provide additional insights or relationships in our data. We could also augment the data to have a bigger training data sets for more refined results. In terms of the accuracy metrics, we could try other models evaluation metrics such as precision, F1-score, or recall to provide more insights to the model's performance to ensure they account for the distribution of classes in the case of imbalanced datasets.